name: Docker Image CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "ramazanabiyev"
          password: "node.js1234"

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ramazanabiyev/getting-started
        context: ./app
      - name: Docker Push
        run: docker push ramazanabiyev/getting-started
